-- CreateTable
CREATE TABLE `TypeData` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `personId` INTEGER NOT NULL,
    `type` VARCHAR(191) NOT NULL,
    `mbti` VARCHAR(191) NULL,
    `extrovertIntrovert` VARCHAR(191) NULL,
    `temperment` VARCHAR(191) NULL,
    `quadra` VARCHAR(191) NULL,
    `sensoryModality` VARCHAR(191) NULL,
    `deModality` VARCHAR(191) NULL,
    `oD` VARCHAR(191) NULL,
    `energyInfo` VARCHAR(191) NULL,
    `function1` VARCHAR(191) NULL,
    `function2` VARCHAR(191) NULL,
    `deciderNeed` VARCHAR(191) NULL,
    `deciderLetter` VARCHAR(191) NULL,
    `observerLetter` VARCHAR(191) NULL,
    `observerNeed` VARCHAR(191) NULL,
    `animal1` VARCHAR(191) NULL,
    `animal2` VARCHAR(191) NULL,
    `animal3` VARCHAR(191) NULL,
    `animal4` VARCHAR(191) NULL,
    `playModality` VARCHAR(191) NULL,
    `sleepModality` VARCHAR(191) NULL,
    `blastModality` VARCHAR(191) NULL,
    `consumeModality` VARCHAR(191) NULL,
    `observerAxis` VARCHAR(191) NULL,
    `deciderAxis` VARCHAR(191) NULL,
    `social` VARCHAR(191) NULL,

    UNIQUE INDEX `TypeData_personId_key`(`personId`),
    INDEX `TypeData_personId_idx`(`personId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
