"""empty message

Revision ID: cd2863d1005e
Revises: 24c011d854d1
Create Date: 2023-05-07 14:57:41.809769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2863d1005e'
down_revision = '24c011d854d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('types', schema=None) as batch_op:
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
