"""empty message

Revision ID: e44aa86f6627
Revises: 0acfb0492370
Create Date: 2023-02-26 10:03:50.107917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44aa86f6627'
down_revision = '0acfb0492370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
